### PR TITLE
the URL field is optional for the maps app

### PR DESCRIPTION
**Pull request by jamesscottbrown**
This was pointed out by @oserban.

### CODE REVIEW

**Comment by senakafdo** [comment]
Wait, why this optional? You either need to select the location that you are launching from an existing state or provide a URL. There is no workaround to this.

**Comment by jamesscottbrown** [comment]
> It is also possible to store these properties in a file with a .json extension and provide its location using the optional url property

https://ove.readthedocs.io/en/latest/ove-apps/packages/ove-app-maps/README.html

**Comment by jamesscottbrown** [comment]
Also, I still think that if no zoom level and location are set, the map should default to the same view as the London Maps demo, and allow the user to pan/zoom to whatever view they want using the controller.

**Comment by senakafdo** [comment]
After chatting with @jamesscottbrown earlier today, we decided to close this PR without merging. 

Users who would not be providing a URL would still need to provide a zoom-level, resolution and location. We cannot open a map at a default location and worse, the zoom-level and resolution are environment specific. It would work out to be different for an entire space vs a sub-section for instance. So, users can chose a preset location (they can change this list and replace it with their own from the drop down. 

The URL is for anyone who has a map configuration and would like to open it. There are some valid use-cases for this (i.e. https://ove.readthedocs.io/en/latest/docs/tutorials/GEOVISUALISATION.html).

**Pull request closed without merging**
